export const portsName = [
  { name: 'Jawaharlal Nehru Port Trust (JNPT)', code: 'INNSA' },
  { name: 'Chennai Port Trust', code: 'INMAA' },
  { name: 'Kolkata Port Trust (Syama Prasad Mookerjee Port)', code: 'INCCU' },
  { name: 'Visakhapatnam Port Trust', code: 'INVTZ' },
  { name: 'Deendayal Port Trust (Kandla)', code: 'INIXY' },
  { name: 'Cochin Port Trust', code: 'INCOK' },
  { name: 'Paradip Port Trust', code: 'INPRT' },
  { name: 'V.O. Chidambaranar Port Trust (Tuticorin)', code: 'INTUT' },
  { name: 'Mormugao Port Trust', code: 'INMRM' },
  { name: 'New Mangalore Port Trust', code: 'INNML' }
];

export const portsDetails = [
  {
    id: 'mumbai',
    name: 'Jawaharlal Nehru Port Trust (JNPT)',
    code: 'INNSA',
    country: 'India',
    rates: {
      portDues: 0.65, // INR per GT
      pilotage: 185, // INR per LOA meter
      towage: 12500, // INR per service
      berthCharges: 1850, // INR per day
      cargoHandling: 285, // INR per ton
      anchorageCharges: 950, // INR per day
      securityCharges: 3500, // INR flat rate
      environmentalFee: 0.35, // INR per GT
      documentationFee: 1250, // INR flat rate
      freshWaterSupply: 85, // INR per ton
      wasteDisposal: 4500, // INR flat rate
    },
  },
  {
    id: 'chennai',
    name: 'Chennai Port Trust',
    code: 'INMAA',
    country: 'India',
    rates: {
      portDues: 0.58,
      pilotage: 165,
      towage: 11500,
      berthCharges: 1650,
      cargoHandling: 265,
      anchorageCharges: 850,
      securityCharges: 3200,
      environmentalFee: 0.32,
      documentationFee: 1150,
      freshWaterSupply: 78,
      wasteDisposal: 4200,
    },
  },
  {
    id: 'kolkata',
    name: 'Kolkata Port Trust (Syama Prasad Mookerjee Port)',
    code: 'INCCU',
    country: 'India',
    rates: {
      portDues: 0.52,
      pilotage: 155,
      towage: 10500,
      berthCharges: 1450,
      cargoHandling: 245,
      anchorageCharges: 750,
      securityCharges: 2950,
      environmentalFee: 0.28,
      documentationFee: 1050,
      freshWaterSupply: 72,
      wasteDisposal: 3850,
    },
  },
  {
    id: 'visakhapatnam',
    name: 'Visakhapatnam Port Trust',
    code: 'INVTZ',
    country: 'India',
    rates: {
      portDues: 0.55,
      pilotage: 158,
      towage: 10800,
      berthCharges: 1550,
      cargoHandling: 255,
      anchorageCharges: 780,
      securityCharges: 3100,
      environmentalFee: 0.30,
      documentationFee: 1100,
      freshWaterSupply: 75,
      wasteDisposal: 4000,
    },
  },
  {
    id: 'kandla',
    name: 'Deendayal Port Trust (Kandla)',
    code: 'INIXY',
    country: 'India',
    rates: {
      portDues: 0.48,
      pilotage: 145,
      towage: 9800,
      berthCharges: 1350,
      cargoHandling: 235,
      anchorageCharges: 680,
      securityCharges: 2850,
      environmentalFee: 0.25,
      documentationFee: 950,
      freshWaterSupply: 68,
      wasteDisposal: 3650,
    },
  },
  {
    id: 'cochin',
    name: 'Cochin Port Trust',
    code: 'INCOK',
    country: 'India',
    rates: {
      portDues: 0.60,
      pilotage: 172,
      towage: 11200,
      berthCharges: 1750,
      cargoHandling: 275,
      anchorageCharges: 820,
      securityCharges: 3350,
      environmentalFee: 0.33,
      documentationFee: 1200,
      freshWaterSupply: 82,
      wasteDisposal: 4350,
    },
  },
  {
    id: 'paradip',
    name: 'Paradip Port Trust',
    code: 'INPRT',
    country: 'India',
    rates: {
      portDues: 0.50,
      pilotage: 148,
      towage: 10200,
      berthCharges: 1400,
      cargoHandling: 240,
      anchorageCharges: 720,
      securityCharges: 2900,
      environmentalFee: 0.27,
      documentationFee: 1000,
      freshWaterSupply: 70,
      wasteDisposal: 3750,
    },
  },
  {
    id: 'tuticorin',
    name: 'V.O. Chidambaranar Port Trust (Tuticorin)',
    code: 'INTUT',
    country: 'India',
    rates: {
      portDues: 0.53,
      pilotage: 152,
      towage: 10600,
      berthCharges: 1500,
      cargoHandling: 250,
      anchorageCharges: 760,
      securityCharges: 3000,
      environmentalFee: 0.29,
      documentationFee: 1075,
      freshWaterSupply: 73,
      wasteDisposal: 3900,
    },
  },
  {
    id: 'mormugao',
    name: 'Mormugao Port Trust',
    code: 'INMRM',
    country: 'India',
    rates: {
      portDues: 0.56,
      pilotage: 160,
      towage: 10900,
      berthCharges: 1600,
      cargoHandling: 260,
      anchorageCharges: 800,
      securityCharges: 3150,
      environmentalFee: 0.31,
      documentationFee: 1125,
      freshWaterSupply: 76,
      wasteDisposal: 4100,
    },
  },
  {
    id: 'new-mangalore',
    name: 'New Mangalore Port Trust',
    code: 'INNML',
    country: 'India',
    rates: {
      portDues: 0.54,
      pilotage: 156,
      towage: 10700,
      berthCharges: 1525,
      cargoHandling: 252,
      anchorageCharges: 770,
      securityCharges: 3050,
      environmentalFee: 0.295,
      documentationFee: 1087,
      freshWaterSupply: 74,
      wasteDisposal: 3950,
    },
  },
];

export const vesselTypes = [
  'Container Ship',
  'Bulk Carrier',
  'Tanker',
  'General Cargo',
  'RoRo',
  'Passenger Ship',
  'LPG Carrier',
  'Chemical Tanker',
  'Car Carrier',
  'Fishing Vessel',
  'Offshore Support Vessel',
  'Dredger',
  'Tug Boat',
];

export const cargoTypes = [
  'Containers',
  'Iron Ore',
  'Coal',
  'Crude Oil',
  'Petroleum Products',
  'Fertilizers',
  'Food Grains',
  'Salt',
  'Limestone',
  'Bauxite',
  'Breakbulk',
  'RoRo Cargo',
  'Passenger',
  'LPG',
  'Chemicals',
  'Vehicles',
  'General Cargo',
  'Textiles',
  'Spices',
  'Tea',
  'Coffee',
];

export const berthTypes = [
  'Container Terminal',
  'Bulk Terminal',
  'Liquid Terminal',
  'General Cargo Berth',
  'RoRo Terminal',
  'Passenger Terminal',
  'Offshore Berth',
  'Iron Ore Terminal',
  'Coal Terminal',
  'Oil Terminal',
  'LPG Terminal',
];